CREATE TABLE tips_shifts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tips DECIMAL(8, 2) NOT NULL,
    hours DECIMAL(8, 2) NOT NULL,
    date_worked DATE NOT NULL,
    job_id INTEGER REFERENCES tips_jobs(id),
    role_id INTEGER REFERENCES tips_roles(id),
    user_id INTEGER REFERENCES tips_users(id),
    date_added TIMESTAMPTZ DEFAULT now() NOT NULL
);