CREATE TABLE tips_paychecks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    check_total DECIMAL(8, 2) NOT NULL,
    date_received TEXT NOT NULL,
    date_added TIMESTAMPTZ DEFAULT now() NOT NULL,
    job_id INTEGER REFERENCES tips_jobs(id),
    user_id INTEGER REFERENCES tips_users(id)
);